In [1]:
print("name")


name


In [8]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
arr[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [18]:
arr2=np.array([1,2,3,4,5,6])
print(arr2[:5:10])

[1]


In [22]:
import pandas as pd

In [29]:
data={"name":['raj','rounak','mohit'],"mark":[90,95,85],"branch":['it','cse','ele']}

In [31]:
d=pd.DataFrame(data,index=['first','second','third'])

In [53]:
print(d)

     name  mark branch
0     raj    90     it
1  rounak    95    cse
2   mohit    85    ele
